<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Photo</name>
   <tag></tag>
   <elementGuidId>08e9ae50-a29f-4d38-886d-1a514fa9f2b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selfie-image-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;selfie-image-upload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>708bd194-8378-4b8f-884b-db682970d5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>selfie-image-upload</value>
      <webElementGuid>bce451f1-e7a4-4bee-a0c8-3641a3695a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfie-image-label</value>
      <webElementGuid>a8aade68-f1d6-4bd3-a6a5-de91491ccf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Photo</value>
      <webElementGuid>d331b0d8-14fe-412e-aa5f-8d4fb33e2c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfie-image-label&quot;)</value>
      <webElementGuid>d2b5190a-50a3-4484-8a89-cdd110647946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='selfie-image-label']</value>
      <webElementGuid>7f37468d-1037-4efb-acf2-ca6bb9c20d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfie-image-preview']/label</value>
      <webElementGuid>4ef41211-e3a6-4ba6-adad-4dc3ddd32570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum File Size 2MB'])[1]/following::label[1]</value>
      <webElementGuid>59437eb6-c1dc-45ad-b752-7fce9133c924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the form below'])[1]/following::label[1]</value>
      <webElementGuid>ccfc9504-af8c-448c-8d28-f2bc7049cb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>6d126f43-da54-4038-871a-a6a4cd33fe24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chosen Services'])[1]/preceding::label[1]</value>
      <webElementGuid>ca5a4872-7408-4578-b7dd-48880de0cf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose Photo']/parent::*</value>
      <webElementGuid>ebec21a3-461f-48cc-a5f5-5d228167c0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>61f1bf9e-46bf-4fa9-8571-1ce6ee6448ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'selfie-image-label' and (text() = 'Choose Photo' or . = 'Choose Photo')]</value>
      <webElementGuid>215d2762-b775-4a3f-999d-e15edadd4cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
