<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trx id</name>
   <tag></tag>
   <elementGuidId>0e81a641-12eb-41b8-8bef-fd2bf2f364ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12f74f03-62dc-4522-8094-fde82cf48241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>2ff3d7af-e1ca-486a-ab79-3291d8000864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>81dc0a02-3f27-4d51-b350-626a4ca17b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AR-10-20220613015316</value>
      <webElementGuid>edd8eef0-ef1e-40f3-98be-2d2f5f3fed8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>162c424a-e17d-4af0-a908-c1772bccaf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68608c6d-4354-4070-b88b-7bb0030e3613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_id&quot;)</value>
      <webElementGuid>60de4f5d-7196-46e6-8d55-8092edbfc200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference_id']</value>
      <webElementGuid>c3d0f95f-7a5d-4f52-97b2-83b7e6c7658a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0b1d7f8d-61d7-45b5-ae39-61aede03c9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference_id' and @placeholder = 'AR-10-20220613015316' and @name = 'reference_id' and @type = 'text']</value>
      <webElementGuid>1d2a0dbd-1055-46a9-83c9-2b01c9e095c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
