<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Photo</name>
   <tag></tag>
   <elementGuidId>5ec3d457-ea91-4b4f-a907-64d619860635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selfie-image-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;selfie-image-upload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ee1011e9-0fbc-4373-a04a-516c7513d362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>selfie-image-upload</value>
      <webElementGuid>f81d048e-a29e-4131-8cf6-23fbd246bde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfie-image-label</value>
      <webElementGuid>1e6ea7a5-9414-4ae1-abd8-f9a680deee13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Photo</value>
      <webElementGuid>353b0290-00a2-40de-8014-d1dba7d81db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfie-image-label&quot;)</value>
      <webElementGuid>c0c78bb7-85cb-4ea1-bb8f-5f59fcb3d338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='selfie-image-label']</value>
      <webElementGuid>0051ef4b-82df-4f39-b407-03d8933a1b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfie-image-preview']/label</value>
      <webElementGuid>1a554bf4-5166-4f53-b487-0cd4d76468a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum File Size 2MB'])[1]/following::label[1]</value>
      <webElementGuid>a814d1ff-8851-4c2c-b2ba-0fa13f932a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the form below'])[1]/following::label[1]</value>
      <webElementGuid>e031b4ad-f33a-40a7-a514-16156d374027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>dd9bac56-52ae-44b7-bc9c-faee5389d83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chosen Services'])[1]/preceding::label[1]</value>
      <webElementGuid>34f10ee9-07ae-46f1-b339-8996d0e63d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose Photo']/parent::*</value>
      <webElementGuid>44a8cb5c-d052-453b-bee9-3f5d70993a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>57488925-4679-41dd-9e28-c5e67cfea21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'selfie-image-label' and (text() = 'Choose Photo' or . = 'Choose Photo')]</value>
      <webElementGuid>213ecee0-9127-4585-809d-a67eea5a9968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
