<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_birhplace</name>
   <tag></tag>
   <elementGuidId>b64597c4-c998-42d2-9263-544effb7ee28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>028aac4e-0271-4b6b-bbdd-c6399eeac399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>347eef8c-389f-4319-850e-ad3ddf390cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>8799cf5c-10ea-40f5-8984-6f98a2b2553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Birth Place</value>
      <webElementGuid>01b4ce70-3fd4-4c44-b29b-1af62b95dfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>6b8f6b97-147c-44eb-885a-e698b7141f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5645d80a-adc3-455c-b81b-5b3b1bdcad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pob&quot;)</value>
      <webElementGuid>c9cf78fe-77e6-4be0-8790-9d46b6f71de0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pob']</value>
      <webElementGuid>b3971d47-05b0-4970-9506-e80cb38e1d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>fe757902-a699-454c-a7c4-a7dda95ce23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pob' and @placeholder = 'Birth Place' and @name = 'pob' and @type = 'text']</value>
      <webElementGuid>cb2d9aff-5b32-4a4c-bc95-4d24d0077f63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
