<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company phone</name>
   <tag></tag>
   <elementGuidId>68455108-f2cf-4ccc-ac3c-ca9677782d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f63040e-0f68-46e2-9b34-7ae2566343d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>d992b761-2aed-4d76-94ff-3b42fae77d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_phone</value>
      <webElementGuid>6806af7a-9686-41d1-8c3c-8fe1fb4142bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Phone</value>
      <webElementGuid>49705f3d-9c03-489b-84e3-2018bd8eda29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_phone</value>
      <webElementGuid>eda6c7b5-1855-4157-816c-8fed8a4749bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebd0c06c-4114-4c18-92b5-91d09d982bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_phone&quot;)</value>
      <webElementGuid>911c2bd4-460c-4b61-bac2-409a90ea6b7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_phone']</value>
      <webElementGuid>bef55b15-c0fc-4b5a-a42e-281fd20db7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>3e04e9b2-5f4c-4176-8373-544d9c697968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'company_phone' and @placeholder = 'Company Phone' and @name = 'company_phone' and @type = 'text']</value>
      <webElementGuid>c8a841bb-b0ac-42cf-a663-4bfcd571bceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
