<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company name</name>
   <tag></tag>
   <elementGuidId>716c9b77-7b6a-447b-96e3-713fbc4af0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12b7e98b-fbad-4f70-affe-1cc088e3a8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>05551949-63e2-46a5-8933-f0a99994bdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>6d45cd1c-025b-4409-bfc0-4710393c0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Name</value>
      <webElementGuid>cf74d0c1-a6c8-4cf4-b501-f5b84101fcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>3e65e30e-830b-479e-8380-95a4d34a9b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>347a93b5-3ced-4378-8a59-d9e80dcf5be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_name&quot;)</value>
      <webElementGuid>406b156e-769f-47ea-bca3-051658717b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_name']</value>
      <webElementGuid>5dd9f341-288a-4d9d-80d7-d8caab4c30ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>027b8dd1-284e-49d5-aab4-a10bb160b15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'company_name' and @placeholder = 'Company Name' and @name = 'company_name' and @type = 'text']</value>
      <webElementGuid>71f51abf-80ae-496a-95ee-bcdc9f3469b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
