<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Photo</name>
   <tag></tag>
   <elementGuidId>4f67ceb7-2737-4727-87ee-ba62bb399ee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selfie-image-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;selfie-image-upload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6bbdd179-0022-44e1-a6d1-7863022fcad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>selfie-image-upload</value>
      <webElementGuid>c3aa821a-60cf-4eac-84a0-24e56ad0cc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfie-image-label</value>
      <webElementGuid>35da775a-e3e8-49bc-abeb-8ce34c4f2104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Photo</value>
      <webElementGuid>095cea7b-68eb-401c-8b71-b8ce2640a707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfie-image-label&quot;)</value>
      <webElementGuid>3d34d47f-eb34-4f27-a71c-00d7ffed5c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='selfie-image-label']</value>
      <webElementGuid>1734edf7-4873-4411-9c7b-7167ca5dbb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfie-image-preview']/label</value>
      <webElementGuid>185df1ca-f264-4570-877f-03ec3cbbe249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum File Size 2MB'])[1]/following::label[1]</value>
      <webElementGuid>cf87a321-4284-4963-91c5-4847334b673a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the form below'])[1]/following::label[1]</value>
      <webElementGuid>6b0e604e-5c18-4d19-855b-26365391a024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>a2976e6e-54af-4e1c-afce-3d4eb219acfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chosen Services'])[1]/preceding::label[1]</value>
      <webElementGuid>0b907b5e-bdb7-4e44-84aa-db7bf65743ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose Photo']/parent::*</value>
      <webElementGuid>3979555f-e49b-4f4a-9806-9211dea03611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>4367a155-10c3-456d-93d1-2e16fdfc0b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'selfie-image-label' and (text() = 'Choose Photo' or . = 'Choose Photo')]</value>
      <webElementGuid>7b17a57c-4ea1-4a9e-8a01-da075633fa7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
