<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Company Verification</name>
   <tag></tag>
   <elementGuidId>95b5943b-65d3-44c3-bbab-df9c7f6e4c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[7]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-label = 'Company Verification' and @name = 'addons[]' and @type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2629eafe-6f06-4f64-93ca-5f001e31c15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addons</value>
      <webElementGuid>21e0f6f8-9218-4cb8-a5d9-660ad4e053f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eea98dd6-e23d-496b-a4ae-c280afb838a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Company Verification</value>
      <webElementGuid>2f95a16a-648a-48a9-a5ff-001e96763908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addons[]</value>
      <webElementGuid>d18611f1-6bd0-4f2c-8456-50d8ded572ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bff68154-7713-4a0a-a202-0180f3469991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>6fd17dc6-c265-42a9-9ad6-c1b7f8a4ee4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 addon-list&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;pretty p-icon p-curve&quot;]/input[@class=&quot;addons&quot;]</value>
      <webElementGuid>0f091921-ec3e-47a1-9245-45be3e081b26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='addons[]'])[3]</value>
      <webElementGuid>e6d500c1-d3e3-437b-8b44-b67c2abd6a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8924d789-e861-47b6-a46f-81cbc723e2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addons[]' and @type = 'checkbox']</value>
      <webElementGuid>50cc4eb6-70ef-4789-bd70-6f3d7aa127a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
