<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Company Headcount Verification</name>
   <tag></tag>
   <elementGuidId>4caad6d6-22ef-4648-8339-afe4ffa6fdb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='addons[]'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-label = 'Company Headcount Verification' and @name = 'addons[]' and @type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3692431-98c5-4225-b86c-19a01a3809a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addons</value>
      <webElementGuid>d28df21e-855f-4bd8-be41-0e57c9bd4ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8025c48e-820f-4e92-8a9e-6217305a236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Company Headcount Verification</value>
      <webElementGuid>1fe9567a-5b96-4950-ade4-8bf38bf31a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addons[]</value>
      <webElementGuid>8a1a1ab6-2b78-45a1-b805-1b995bb1d08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f9054fca-e378-4950-a0b3-069187a4f351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>b653d56b-8377-419b-a589-9fe5a1e26eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 addon-list&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;pretty p-icon p-curve&quot;]/input[@class=&quot;addons&quot;]</value>
      <webElementGuid>163a1535-8249-445f-9f86-fe52e6a21e68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='addons[]'])[4]</value>
      <webElementGuid>ac88af7b-92d2-4797-b99c-29f7750c9e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>cef2e902-a36d-4f32-8c4f-c0b4c5d014b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addons[]' and @type = 'checkbox']</value>
      <webElementGuid>a339787c-fc20-47a1-a23b-987bfaff0ccf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
