<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Company Capital Verification</name>
   <tag></tag>
   <elementGuidId>e5c81478-6103-4552-8c7c-810b3dd5adf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;addons[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='addons[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eed79b37-b628-4bfb-8963-7e84ba8afc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addons</value>
      <webElementGuid>62efb22e-71b7-4b3e-93d6-470fd4b09b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>58ac0925-f660-4933-af68-ba3553822559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Company Capital Verification</value>
      <webElementGuid>e9227a4b-e5e0-4f40-9fb5-36ebc2dd7b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addons[]</value>
      <webElementGuid>9c644605-6130-46a4-b385-bd34144b3947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8bde92d2-4605-4c64-93bf-d7f29a9635e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>9f68e2da-9e05-4994-8a62-52745dbff3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 addon-list&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;pretty p-icon p-curve&quot;]/input[@class=&quot;addons&quot;]</value>
      <webElementGuid>4e8318fe-9811-4844-a460-3fe164a994ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='addons[]']</value>
      <webElementGuid>e191f9a8-a7a6-4ec4-8ff9-aacef3146951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7ad2f62e-c509-484a-ac4a-4fdbf6f14591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addons[]' and @type = 'checkbox']</value>
      <webElementGuid>b9c35e48-d07b-4b51-88ee-ab7d0eb1ce4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
