<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Biometric Plus Verification</name>
   <tag></tag>
   <elementGuidId>173abf57-2ae0-493e-8685-32aefba75108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='addons[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;addons[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c8a4caa-28cc-4596-abe4-ce5f9ab7c323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addons</value>
      <webElementGuid>0c432668-d35d-47d4-b73c-2e16a7156f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>940b6852-6558-431b-a1dc-6630e1d1cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Biometric Plus Verification</value>
      <webElementGuid>ea119c21-9aa2-4e2a-94d7-3033a3b5f742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addons[]</value>
      <webElementGuid>9b703b0e-a76f-485f-83a7-c47319730bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>240ab501-53f4-407d-aa6f-b993231cba9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>85c90058-e60c-4cd1-8c4e-d788ae42bce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 addon-list&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;pretty p-icon p-curve&quot;]/input[@class=&quot;addons&quot;]</value>
      <webElementGuid>88dec812-dae1-418b-af40-32b74f44dea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='addons[]']</value>
      <webElementGuid>3a470aae-a219-485d-94c8-3efd23323df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>16e8cb64-74d1-4ee3-8168-94cdf8a8a163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addons[]' and @type = 'checkbox']</value>
      <webElementGuid>9126265f-347f-4547-8a09-06e858627864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
