<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_decreedate</name>
   <tag></tag>
   <elementGuidId>9f085779-4434-47f2-91da-dc32b963d339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decreedate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#decreedate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>753255d3-561d-4984-8108-7f6f7da34def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>53459431-9a1f-4d23-a96f-ab1ef3ca2b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decreedate</value>
      <webElementGuid>d2df2c91-780b-4328-ba92-8dafaaf31662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Decree Date (31-01-1980)</value>
      <webElementGuid>5aced9e6-008a-4adb-af13-108b6037a500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decreedate</value>
      <webElementGuid>4bddc51c-48eb-40ee-9be8-0f1a7dfd7f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4702a27c-7b20-43bc-b423-ec23627ed4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0a69bbdf-3b70-4c04-a01e-50e925779594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decreedate&quot;)</value>
      <webElementGuid>71d97430-8207-4e72-a434-88b8303c066f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decreedate']</value>
      <webElementGuid>ce9adcd1-b6fe-4d5a-9827-058e78e19706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>895ea1b0-e5d9-46d0-83b0-f4e9e227055f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decreedate' and @placeholder = 'Decree Date (31-01-1980)' and @name = 'decreedate' and @type = 'text']</value>
      <webElementGuid>703bfefb-4dcb-48f2-9513-3ff3f344c0a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
