<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_decreeno</name>
   <tag></tag>
   <elementGuidId>705e1c8e-81f5-48c8-a30c-80ad018d01f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decreeno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#decreeno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d757718a-d9c6-4e2b-9708-50ebbd428abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>8e6b4dd1-c571-4e3b-aab3-f87b308a8d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decreeno</value>
      <webElementGuid>3f42d839-07cb-4606-b1d2-004728beb523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Decree No</value>
      <webElementGuid>91102040-69c5-49b8-a13a-7f8efc4db658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decreeno</value>
      <webElementGuid>5938547f-b4e1-4147-a88d-fb1b9f80a368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcab77ce-8602-4c71-b47f-9b99b61a5ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decreeno&quot;)</value>
      <webElementGuid>26be97f7-c40a-4810-be2e-979cc0fff866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decreeno']</value>
      <webElementGuid>cfc5e4f5-c365-4276-affb-f585dd944b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>96608861-b577-4684-a04c-57a2c06073d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decreeno' and @placeholder = 'Decree No' and @name = 'decreeno' and @type = 'text']</value>
      <webElementGuid>ed70f113-5685-4cc1-8437-8bc8aaf790d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
