<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trx id</name>
   <tag></tag>
   <elementGuidId>fd969344-9b84-4d8e-afc3-8b68e274232d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f30c698-10d2-4573-83a8-f5af5178868e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>c9c679f9-8d86-4107-aa71-bd7c66a46721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>c2a16afb-3899-4f26-9fe2-63445c244d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AR-10-20220608114730</value>
      <webElementGuid>330b611a-5ca3-4f61-93e6-28368d059286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>5c39b43f-44e7-4d9a-91ba-726d54c17efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc4dfd49-3eb3-4108-8253-725ff280bf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_id&quot;)</value>
      <webElementGuid>7e75e85c-92d1-45e9-82de-e9ef5feba7a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference_id']</value>
      <webElementGuid>393c1821-f051-4167-a76c-9d10d20808e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>022cf9d1-d22a-40ca-bb05-5b7d82daf338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference_id' and @placeholder = 'AR-10-20220608114730' and @name = 'reference_id' and @type = 'text']</value>
      <webElementGuid>7217dffb-dc75-4055-932c-278794f332a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
