<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_income</name>
   <tag></tag>
   <elementGuidId>f076fde2-e690-479a-8c37-387e76a9323a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_income</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_income']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03714c0c-4bc8-442f-8fac-e86f310637ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>6ede7cef-ecf2-4246-92c7-a2a9f76d8b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_income</value>
      <webElementGuid>f3abe4b0-9f51-4689-a8ec-dbd7eb79a00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Income (Monthly)</value>
      <webElementGuid>6f55be86-be38-4583-8bf9-dcc0172c7862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal_income</value>
      <webElementGuid>a5e06fd5-55ac-4ac7-8429-47dcadc6e05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af8d403e-491b-4658-8db4-024b3934ea82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_income&quot;)</value>
      <webElementGuid>bfd4d5cd-b616-4b4e-9649-ed7753913bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_income']</value>
      <webElementGuid>b193f4aa-bf70-4b83-854a-a905c05e1998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>d0ac9114-a9b5-4f2c-bdba-a251a7e076a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_income' and @placeholder = 'Income (Monthly)' and @name = 'personal_income' and @type = 'text']</value>
      <webElementGuid>e74b956f-391a-48d9-a196-fc07462ae61b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
