<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transactions_text</name>
   <tag></tag>
   <elementGuidId>b82dc8f2-bdc4-4e3e-8f96-d346fa42a730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Transactions' or . = 'Transactions')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transactions</value>
      <webElementGuid>eeae7e0f-7f37-4e28-9bce-9e9efdf4887c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transactions</value>
      <webElementGuid>a95ea001-8a9a-4f0f-9728-00634d81e77c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
