<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_birthplace</name>
   <tag></tag>
   <elementGuidId>f04fbeba-6282-4bdd-a2e8-0a8adea5d330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18082706-6473-4964-8620-7171a33e629f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>c3bd5edd-1978-4008-b198-7f6902881e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>fad4fb79-da67-4ac7-aa9f-fbffdad15ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Birth Place</value>
      <webElementGuid>7f493898-d1db-47aa-894f-f416939ddf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>026d8eb7-bf60-4113-819a-4974db0e66fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>b381d08f-5108-45c2-a10f-02c29bfd5aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e5d5480-b3b4-4249-9d12-aaba08fa64c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pob&quot;)</value>
      <webElementGuid>ef48a473-00f5-46a3-be26-4b6bf43acc44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pob']</value>
      <webElementGuid>d0bdffde-6ee6-4c75-91a0-5c5d9820338e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b27cbf0b-70a0-4255-9eb7-8ab45ba28dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pob' and @placeholder = 'Birth Place' and @name = 'pob' and @type = 'text']</value>
      <webElementGuid>9cded0d4-e61b-4ca6-bb0f-5deea3264b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
