<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nik</name>
   <tag></tag>
   <elementGuidId>5650fd95-7aa8-4020-9958-dbaf01095ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nik']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e9064c7-dcef-427b-b2a6-06736f27b1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>a7a52a2b-7afd-4508-94de-6306234b7c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>b381560d-3c65-4a4e-996b-a2a4425819e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>d46628a5-b3c2-4220-8fe4-ef0fd075a5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ed610722-1730-4c5a-a892-9f550efd8839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>6d58f934-7545-4a52-b848-f8a532311a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>dbe71d11-bb68-4f7b-ac89-f0734c572920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f64f65e8-7007-4bed-88e8-0be0cffb43d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik&quot;)</value>
      <webElementGuid>6efa00d0-54fe-4b24-a794-e6c55a7d978c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>44fce2e7-e762-4a4e-94c8-1e45474f27ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik']</value>
      <webElementGuid>5c9411dd-d052-45ac-a3b0-c2d633577579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>218bea75-36b8-4579-b4e3-30454df1262a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nik' and @placeholder = 'NIK' and @name = 'nik' and @type = 'text']</value>
      <webElementGuid>bf3fe71d-d337-4e41-887a-33f8c6d16f8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
