<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trx_id</name>
   <tag></tag>
   <elementGuidId>e8e54cde-b380-4e2a-89a1-0cc91ee7b166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de1c0624-eec5-49df-9361-5e0ebf58ad81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>7ccfe6b0-3c81-48ca-8008-ab95840380a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>99ac4ee4-cc29-47d2-bd72-45ff64e63be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AR-4-20230329052753</value>
      <webElementGuid>f46fe34b-0532-4f6c-b516-ce6d55ade42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>148b2e14-4af9-4a66-ba0a-104b162ab0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78e49642-71e3-426a-8bc5-a86e2dddcbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_id&quot;)</value>
      <webElementGuid>081d4b2a-fe71-4301-a2bb-3e0f673fb235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference_id']</value>
      <webElementGuid>3ca9b634-2248-43cc-8b0e-01e88698bc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ff44dc7d-fdca-4781-986d-e5fffe910714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference_id' and @placeholder = 'AR-4-20230329052753' and @name = 'reference_id' and @type = 'text']</value>
      <webElementGuid>d3e58d2e-987c-4ead-b30b-959c8d06b402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
