<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_npwp</name>
   <tag></tag>
   <elementGuidId>f2818cad-e390-4e28-b7df-f35c6e1509ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_npwp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal_npwp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dfa77ad-de44-4c4b-a012-343f69caea64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>91e4721c-14a4-401a-ab3d-69d577ad60b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_npwp</value>
      <webElementGuid>9cb47d83-86ff-43ed-9d5a-c56d20c2f6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NPWP</value>
      <webElementGuid>c838b01a-7561-4d25-bdca-74edf7984f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal_npwp</value>
      <webElementGuid>da911c82-d91a-4705-a95a-064e71208f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9e95a43-2f15-4b7b-9b77-337b4c647745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_npwp&quot;)</value>
      <webElementGuid>eb9aaf7d-21e5-4c15-8cc3-943e8a89ac64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_npwp']</value>
      <webElementGuid>20bca29f-94f2-47ea-a08b-71a3f32bf0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f29d1907-4871-40d0-8e8c-207307ff3f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_npwp' and @placeholder = 'NPWP' and @name = 'personal_npwp' and @type = 'text']</value>
      <webElementGuid>7d6024bf-f56a-47af-9c31-3ca975c048a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
