<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_error_selfie_photo</name>
   <tag></tag>
   <elementGuidId>2557e655-8407-4d72-b631-7228923197ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selfie-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87d73b25-dce6-449b-bbe1-00ed07175426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfie-error</value>
      <webElementGuid>174d8813-1bb2-4022-b87f-6e0ce755e080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>invalid-feedback text-center</value>
      <webElementGuid>84824dee-81fb-4226-94dc-f6fb146c8ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            The selfie must be a file of type: jpeg, jpg, png.
                        </value>
      <webElementGuid>22bfee00-ff7a-4744-8739-a5b677ddc00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfie-error&quot;)</value>
      <webElementGuid>d04d0817-a293-40d3-b896-86d4021bc90f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='selfie-error']</value>
      <webElementGuid>66b69907-206a-4586-9f3c-e1372ea7518a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Photo'])[1]/following::div[2]</value>
      <webElementGuid>021444cd-cee9-413b-8043-b820d79e453a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the form below'])[1]/following::div[7]</value>
      <webElementGuid>987f49d8-b241-4e11-8e15-1239910a2424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[1]/preceding::div[4]</value>
      <webElementGuid>d21c5eb4-4753-47ca-a2fb-7e013f43298b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[2]/preceding::div[9]</value>
      <webElementGuid>6b435c15-0da4-4f03-83de-e78e1d83c325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The selfie must be a file of type: jpeg, jpg, png.']/parent::*</value>
      <webElementGuid>eefa9bee-7c16-4094-b72b-09d807f3adca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>acc41f6f-28c7-47d1-917d-538230a99a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'selfie-error' and (text() = '
                            The selfie must be a file of type: jpeg, jpg, png.
                        ' or . = '
                            The selfie must be a file of type: jpeg, jpg, png.
                        ')]</value>
      <webElementGuid>f0824724-0d66-4b7e-b09f-f1270d407d5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
