<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trx_id</name>
   <tag></tag>
   <elementGuidId>33264c56-1826-4c3e-ac6b-e2172d50112d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2393bbbb-adbd-4ac5-811f-29423ffbf862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>07072d3f-b0ae-4974-a99b-d28ce231f426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>05179a6f-0ec3-4275-8ddc-14842d991d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AR-4-20230330103655</value>
      <webElementGuid>cc4bd7e0-c278-4edf-80cc-fad0cf2eb85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>b3dc8aed-b9fc-4f2e-9452-4f7640dda6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19a094b2-b8c5-483d-8f97-2abe81a42313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_id&quot;)</value>
      <webElementGuid>a57f14d0-e8a0-48e4-be6c-12b32a303d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference_id']</value>
      <webElementGuid>1c3fd114-511c-4b10-9be1-2d26819f1d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5e5c94cb-3e44-46fe-bfbf-483cba680b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference_id' and @placeholder = 'AR-4-20230330103655' and @name = 'reference_id' and @type = 'text']</value>
      <webElementGuid>3e92d262-4391-4946-b991-ac3cf70ff770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
