<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mother_name</name>
   <tag></tag>
   <elementGuidId>01587048-bbdb-44fd-9ec4-31e759846432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mother_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mother_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e01afe4-03b5-4dc0-853d-bfcc737c5092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>2a6d6e13-adec-41fb-a4f3-d4bb4613521b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mother_name</value>
      <webElementGuid>93e08578-b784-48d2-a114-8964149d408f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mother Name</value>
      <webElementGuid>bd10c86d-1ea0-4859-99f7-e3806477a7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mother_name</value>
      <webElementGuid>87474ff9-5379-46e0-9225-7fc037355ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b4c49ff-5150-49c1-a396-096c3c54ee65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mother_name&quot;)</value>
      <webElementGuid>c7cad0a2-e8a4-4b65-be8a-76b1b67650f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mother_name']</value>
      <webElementGuid>34c6ed71-819f-4615-a3f7-fe404d3bf601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>3ba4ddcd-f51b-4f4a-87fd-2efc6aed4527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mother_name' and @placeholder = 'Mother Name' and @name = 'mother_name' and @type = 'text']</value>
      <webElementGuid>e8ff6e17-cf59-4502-9814-dcbbadeb60e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
