<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selfie_photo</name>
   <tag></tag>
   <elementGuidId>25ab5c87-8e8f-453f-89b7-f7846bc45d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selfie-image-upload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selfie-image-upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ed1c850-e0eb-4273-97d8-bdacd59c5f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfie-image-upload</value>
      <webElementGuid>c7f3d4b9-f52a-4f73-b2f3-a37f984bcdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selfie</value>
      <webElementGuid>414889a2-b4cc-42f5-a1cf-2fcdce899499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>c04cc37e-9291-40ab-b18c-fd25625b3e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfie-image-upload&quot;)</value>
      <webElementGuid>ebc18cde-fd85-48ac-af9b-907c991fd7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selfie-image-upload']</value>
      <webElementGuid>da11e638-57db-4772-ac2a-49e09112b43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfie-image-preview']/input</value>
      <webElementGuid>421a6172-0c55-49b7-a88e-f3bdacfc9f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>fb4f3c3e-4fe6-4ee4-a4a9-1aef973a707f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'selfie-image-upload' and @name = 'selfie' and @type = 'file']</value>
      <webElementGuid>6014bab4-d6ad-4360-afa3-cb0e34ef0839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
