<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_files_photo</name>
   <tag></tag>
   <elementGuidId>2457ffd9-b1d7-4234-a294-0571314519d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='doc_file'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file' and @name = 'doc_file[]' and @id = 'doc_file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c761ef9e-37f3-4811-aff5-66c3c4ae5008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e4368038-117a-453b-9cfe-2bdd0c10dac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doc_file[]</value>
      <webElementGuid>8a309fcd-a9ff-4a18-b396-8667f8e79241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doc_file</value>
      <webElementGuid>38300def-12b0-4beb-a5da-abe07ff14d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>47155042-6135-4e9b-9ab0-d99b586d0517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/form[@class=&quot;uiblock&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;input-field col-md-12&quot;]/div[@class=&quot;input relative&quot;]/input[@id=&quot;doc_file&quot;]</value>
      <webElementGuid>e5dcd196-14dd-4d32-8bc6-9eb611aad988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='doc_file'])[6]</value>
      <webElementGuid>0cc84cb8-abc4-409b-8cb7-f46dbf08e5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/input</value>
      <webElementGuid>f2f27219-461f-4fc5-a44e-0d546465d8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'doc_file[]' and @id = 'doc_file']</value>
      <webElementGuid>e4b0f75c-9292-42d1-98d9-693386a9dfe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
