<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_npwp_photo</name>
   <tag></tag>
   <elementGuidId>e5dada65-8fb9-48a3-b10f-f75d9d29b53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;doc_file[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b9f54aa-2454-4df8-aaa7-dcdb8049484c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>5d9d2004-bc96-49dd-85e6-d15221a4d39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doc_file[]</value>
      <webElementGuid>88fbf52b-7310-44ce-bc87-df329bdc050f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5eb5981d-ab7f-431a-8fba-96af091671a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/form[@class=&quot;uiblock&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;input-field col-md-12&quot;]/div[@class=&quot;input relative&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>aa440dec-143a-419c-920a-40acd0a27f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='doc_file[]']</value>
      <webElementGuid>804f249b-5f44-469f-bf38-e13e3ef3de40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>363ef50d-d802-4f43-8a14-5cc70da8baf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'doc_file[]']</value>
      <webElementGuid>6ba2eabd-17f1-4070-84ba-f898bba6ff1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
