<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trx id</name>
   <tag></tag>
   <elementGuidId>edfd23eb-5b39-4a1d-bf02-9fe46135b764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ea46e67-b605-4a24-bd4b-de2035aad092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>914a5062-87d7-488f-b439-3263f4c981a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>0f8f1574-d632-462d-8c64-8b1fad6feb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AR-10-20220617024844</value>
      <webElementGuid>8150730a-b1af-4732-9335-63a515e09dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference_id</value>
      <webElementGuid>bbd01c90-0a58-4572-811a-71519043b596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d673f0e7-1f9d-4509-a00c-0ffd9ea598a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_id&quot;)</value>
      <webElementGuid>a9fc4bf9-746e-4d1c-a168-df8811548dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference_id']</value>
      <webElementGuid>81c8a9da-aebb-4d12-a015-26ab948b3187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>76c127c4-2ee6-4682-8af5-47f06dfb8722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference_id' and @placeholder = 'AR-10-20220617024844' and @name = 'reference_id' and @type = 'text']</value>
      <webElementGuid>6c5c6d5e-cfde-49a1-819e-0596c7a2decf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
