<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone</name>
   <tag></tag>
   <elementGuidId>da2adf10-6666-49c2-97f0-33438c9ee9ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d79d5ce-5489-423a-8113-b2f73575135c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>735af72f-60a7-4f62-ad2a-f4e2b7889813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>30205c89-4074-4d20-adb1-2093ea4d7b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number (08xxxxxxxxxx)</value>
      <webElementGuid>8e0d76eb-bf56-4691-94e1-919c903614b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>07420d24-3be8-437a-9bf2-2ec2ab8b8615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c19dfd4-0512-40b2-8c90-faf2996fee5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a95c5a7a-2e49-49c2-b805-f737bd83d9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone&quot;)</value>
      <webElementGuid>67311c57-a986-4b21-969b-312a7c27e548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone']</value>
      <webElementGuid>ce706a33-af7b-4bea-9395-e4eef834df44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>02afa7c3-390d-4557-bae5-fd80330e0f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone' and @placeholder = 'Phone Number (08xxxxxxxxxx)' and @name = 'phone' and @type = 'text']</value>
      <webElementGuid>d876b9a3-0ad6-4fa1-b282-811ea39b5bb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
