<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_decreeno</name>
   <tag></tag>
   <elementGuidId>f1837e29-56e9-49cc-9284-fedf111e4f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#decreeno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decreeno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab588873-e885-4138-9d8f-2fccd8362bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>ebd47eed-9999-4f8b-a59e-2b61ee296835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decreeno</value>
      <webElementGuid>e184eddd-cbca-43db-8216-0f01947f60f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Decree No</value>
      <webElementGuid>937510b1-aa79-41da-a61c-82ca4f3835fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decreeno</value>
      <webElementGuid>bc4bf8db-a21b-4008-96e0-8e5da27db1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>333845d9-c702-414f-8b04-045fc08b084c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decreeno&quot;)</value>
      <webElementGuid>6fa42dd2-5ad4-45db-a993-ced0e4d42e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decreeno']</value>
      <webElementGuid>a96c8659-e6e4-456d-8a91-3d9f55b3bb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9e9d66dc-191a-42e3-a719-632047f8da1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decreeno' and @placeholder = 'Decree No' and @name = 'decreeno' and @type = 'text']</value>
      <webElementGuid>a51673cc-df68-47d5-90b1-d315e50e431b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
