<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_birthplace</name>
   <tag></tag>
   <elementGuidId>0566693e-a11e-48a5-93d4-12251f6d0cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01d9f993-85db-4975-a703-1296964a4dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>203d660c-89e2-468e-83ff-8eec95e6ee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>6d30bffa-3a97-402e-98f6-664f2e4d2dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Birth Place</value>
      <webElementGuid>40c7490e-60a1-445b-b44d-7bbeaab1d8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f4e63dce-bc97-4bfd-8e35-bfb496507d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>5bf91c95-48eb-407a-9cc3-9ef0c7baaa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8baf8234-cec1-4aa8-9292-012987bc2951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pob&quot;)</value>
      <webElementGuid>0d391662-586d-4dda-bf88-b18448763054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pob']</value>
      <webElementGuid>28bb2bf2-a18d-4087-8ed7-ed20c8b3e914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>1fa03bac-c3ff-4947-bbf7-f3aae2abd1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pob' and @placeholder = 'Birth Place' and @name = 'pob' and @type = 'text']</value>
      <webElementGuid>d4b5b8b1-7914-4281-a1aa-8c858ee8305f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
