<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nik</name>
   <tag></tag>
   <elementGuidId>9cd67967-47d0-42d0-ac47-562485fe3981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nik']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a033fbbc-71ba-4087-b3e0-73cf0132e624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>aad18075-c118-4282-b037-bca59d138c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>ce0fa4bf-49b5-47b3-af53-4bf4522efba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>bac02525-a6d7-4b6c-889f-411d1529c47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f88eeb04-0f1c-462f-a0a5-77984a4e55bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>012d1cdd-f6e1-4711-b3c6-bca5a337c40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>03e284bb-57f7-4dff-8873-9c348f8256ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95a135b8-b371-41b8-8855-2bf6b7e9e3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik&quot;)</value>
      <webElementGuid>13d49346-d48b-4587-b074-50c755c9c9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>85a2dc04-1a5e-463e-a459-1e906c029c67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik']</value>
      <webElementGuid>8451389a-0e41-4d1d-a299-500382a56a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8117053e-6ddf-4dab-bbda-3ee8e93ed8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nik' and @placeholder = 'NIK' and @name = 'nik' and @type = 'text']</value>
      <webElementGuid>f15e5217-e9c6-4d8d-9cb9-d1a7daccdcec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
