<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link copy url</name>
   <tag></tag>
   <elementGuidId>15d603ec-37f0-4fd7-881a-504cd7ecf96e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/section/div[2]/div[1]/div/div[5]/span[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>08635c2a-75e9-40b9-8306-61029c5a8c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please fill out the form below</value>
      <webElementGuid>42ad3aa5-720e-44bf-a778-502a8fefdaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;container&quot;]/h3[1]</value>
      <webElementGuid>91758168-8f33-421c-b388-d32c7cff0270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::h3[1]</value>
      <webElementGuid>86fd8280-6eb3-4fee-b4e8-797ca933c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chosen Services'])[1]/preceding::h3[1]</value>
      <webElementGuid>cb449d55-171b-474c-925b-567dc3d707c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please fill out the form below']/parent::*</value>
      <webElementGuid>5703bf9b-f5ab-4a58-82f6-dc2cb61b47b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>66aeab41-bfb9-48c3-9f45-f6ecd52b0a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Please fill out the form below' or . = 'Please fill out the form below')]</value>
      <webElementGuid>462d581b-e9b7-4f7f-be59-f00ce2fc102a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
